from core.ambiente import (
    TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
)

"""CONFIGURAÇÕES DO CANAL GRATUITO"""
# 💬 CANAL DO TELEGRAM
INTERVALO_ATUALIZAR_DESCRICAO = 300
INTERVALO_MENSAGEM_PROMOCIONAL = 1800
INTERVALO_MENSAGEM_HEADER = 5400
INTERVALO_ATUALIZACAO_STREAMERS = 5400

# 🔄 SWITCHES DE FUNCIONALIDADE
MODO_MONITORAMENTO = "MODO_LOUCO"  # Opções: MODO_PADRAO, MODO_CIRURGICO, MODO_LOUCO
TIPO_LOG = "PADRAO"  # "PADRAO" ou "DESENVOLVEDOR"
ATUALIZAR_DESCRICAO = True
ENVIAR_CLIPES = True
USAR_VERIFICACAO_AO_VIVO = True

"""CONFIGURAÇÕES DO CHAT PRIVADO"""
MODO_MANUTENCAO = False
GATEWAY_PAGAMENTO = "KIRVANO"  # 'MERCADOPAGO' ou 'KIRVANO'