from core.ambiente import (
    TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
)

"""CONFIGURAÇÕS DO CANAL GRATUITO"""
# 🎮 LÓGICA DO MONITORAMENTO
STREAMER = "loud_coringa"
MODO_MONITORAMENTO = "MODO_PADRAO"  # MODO_LOUCO, MODO_PADRAO, MODO_CIRURGICO

# 💬 CANAL DO TELEGRAM
INTERVALO_ATUALIZAR_DESCRICAO = 300
INTERVALO_MENSAGEM_PROMOCIONAL = 1800
INTERVALO_MENSAGEM_HEADER = 0
INTERVALO_ATUALIZACAO_STREAMERS = 0

# 🔄 SWITCHES
TIPO_LOG = "PADRAO"  # "PADRAO" ou "DESENVOLVEDOR"
ATUALIZAR_DESCRICAO = True
ENVIAR_CLIPES = True
USAR_VERIFICACAO_AO_VIVO = True

"""CONFIGURAÇÕS DO CHAT PRIVADO"""
# CONFIGURAÇÕES
MODO_MANUTENCAO = True