from core.ambiente import (
    TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
)


#IDs dos usuários administradores do bot
ADMIN_TELEGRAM_IDS = [1527996001]


"""CONFIGURAÇÕES DO CANAL GRATUITO"""
# 💬 CANAL DO TELEGRAM
INTERVALO_ATUALIZAR_DESCRICAO = 300
INTERVALO_MENSAGEM_PROMOCIONAL = 800
INTERVALO_MENSAGEM_HEADER = 5400
INTERVALO_ATUALIZACAO_STREAMERS = 5400

# 🔄 SWITCHES DE FUNCIONALIDADE
MODO_MONITORAMENTO_GRATUITO = "AUTOMATICO" # Opções para o canal gratuito: 'AUTOMATICO' (sensibilidade baseada em viewers) ou 'MANUAL' (usa as constantes de `canal_gratuito/core/monitor.py`)
TIPO_LOG = "DESENVOLVEDOR"  # "PADRAO" ou "DESENVOLVEDOR"
ATUALIZAR_DESCRICAO = True
ENVIAR_CLIPES = True
USAR_VERIFICACAO_AO_VIVO = True

"""CONFIGURAÇÕES DO CHAT PRIVADO"""
MODO_MANUTENCAO = False
GATEWAY_PAGAMENTO = "KIRVANO"  # 'MERCADOPAGO' ou 'KIRVANO'
SUPPORT_USERNAME = "euw3ll" # Usuário para o botão de suporte