from canal_gratuito.config import (
    TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
)

# 🎮 LÓGICA DO MONITORAMENTO
STREAMER = "loud_coringa"
INTERVALO_SEGUNDOS = 90  # Janela para agrupar clipes próximos
INTERVALO_MONITORAMENTO = 30  # Frequência entre verificações

# 💬 CANAL DO TELEGRAM
INTERVALO_ATUALIZAR_DESCRICAO = 300
INTERVALO_MENSAGEM_PROMOCIONAL = 600 
INTERVALO_MENSAGEM_HEADER = 3600 
INTERVALO_ATUALIZACAO_STREAMERS = 3600 

# 🔄 SWITCHES
TIPO_LOG = "PADRAO"  # "PADRAO" ou "DESENVOLVEDOR"
ATUALIZAR_DESCRICAO = True
ENVIAR_CLIPES = True
USAR_VERIFICACAO_AO_VIVO = True
